# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sensor_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


# Nota: este fichero se genera automáticamente ejecutando:
#   python -m grpc_tools.protoc -I. --python_out=. sensor_data.proto
#
# El esquema fuente (sensor_data.proto) define el mensaje AirQualityEvent
# con 13 campos: name, timestamp (int64), pm10/no2/so2 (double) y
# los tags city, project, asset_id, location, host, node_id,
# anomaly, anomaly_type (todos string).
#
# No editar manualmente. Regenerar si se modifica sensor_data.proto.

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11sensor_data.proto\x12\nairquality\"\xe3\x01\n\x0f\x41irQualityEvent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x0c\n\x04pm10\x18\x03 \x01(\x01\x12\x0b\n\x03no2\x18\x04 \x01(\x01\x12\x0b\n\x03so2\x18\x05 \x01(\x01\x12\x0c\n\x04\x63ity\x18\x06 \x01(\t\x12\x0f\n\x07project\x18\x07 \x01(\t\x12\x10\n\x08\x61sset_id\x18\x08 \x01(\t\x12\x10\n\x08location\x18\t \x01(\t\x12\x0c\n\x04host\x18\n \x01(\t\x12\x0f\n\x07node_id\x18\x0b \x01(\t\x12\x0f\n\x07\x61nomaly\x18\x0c \x01(\t\x12\x14\n\x0c\x61nomaly_type\x18\r \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AIRQUALITYEVENT']._serialized_start=34
  _globals['_AIRQUALITYEVENT']._serialized_end=261
# @@protoc_insertion_point(module_scope)
